---
name: module3_task1
"on":
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  builds:
    name: up-to-date installation system
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set execute permissions
        run: |
          cd module3_task1
          chmod +x setup.sh
      - name: Run setup.sh
        run: |
          cd module3_task1
          sudo ./setup.sh
      - name: Makefile
        run: |
          make help
          make build
          make run
          make stop
          make clean
        working-directory: module3_task1
