---
name: module3_task3
"on":
  push:
    branches:
      - main
    tags:
      - "1.0.0"
  schedule:
    - cron: '0 0 * * *'
jobs:
  builds:
    permissions: write-all
    name: up-to-date installation system
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set execute permissions
        run: |
          cd module3_task3
          chmod +x setup.sh
      - name: Run setup.sh
        run: |
          cd module3_task3
          sudo ./setup.sh
      - name: Validate Makefile execution make build command
        run: |
          make help
          make build
          make lint
          make run
          make stop
          make clean
        working-directory: module3_task3
      - name: packaging
        run: cd module3_task3 && make package
      - name: tests
        run: |
          cd module3_task3/ && make test
      - name: archieve ZIP file artifact only if all tests sucess
        if: ${{github.ref=='refs/heads/main'}}
        uses: actions/upload-artifact@v3
        with:
          name: Saving the zip file
          path: |
            module3_task3/awesome-website.zip
      - name: construct Release.txt
        run: cat ./module3_task3/DEPLOY.md >> Release.txt

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/1.0.0')
        with:
          files: |
            awesome-website.zip
            DEPLOY.md
          body: |
            ## body
      - run: gh release create v1.0.0 --title "v1.0.0"
            --notes DEPLOY.md 2>/dev/null || echo "OK"
